@echo off
set PATH=C:\Program Files\nodejs;C:\Users\amele\AppData\Roaming\npm;%PATH%
cd /d "C:\Users\amele\OneDrive\Desktop\Anthony Personal\Golf App\backend"
echo Setting NODE_ENV...
call npx @railway/cli variables set NODE_ENV=production
echo Setting PORT...
call npx @railway/cli variables set PORT=3001
echo Setting JWT_SECRET...
call npx @railway/cli variables set JWT_SECRET=linkup-golf-super-secret-jwt-key-2024
echo Setting CORS_ORIGIN...
call npx @railway/cli variables set CORS_ORIGIN=https://frontend-dfx-e2ecc1c4.vercel.app
echo.
echo Variables set. Listing current variables...
call npx @railway/cli variables
